# Generated by Django 3.2.8 on 2021-10-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0037_gitremote'),
        ('galaxy', '0025_add_content_guard_to_distributions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGRole',
            fields=[
                ('gitremote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='gitremote', serialize=False, to='ansible.gitremote')),
            ],
            options={
                'abstract': False,
                'default_related_name': 'gitremote',
            },
            bases=('ansible.gitremote',),
        ),
    ]
